development:
  secret_key_base: 8c085afc80b2fad90766199bb7b4e2a4d87c5ee2895d762f296059ad960caffae3d0a04a29af30506b0da829c866d3c081622e14ab64f00210a7215cf26e6116
  aws_key_id: <%= ENV["AWS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  csd_endpoint: http://search-ml-test-desuye5rn55qjlzjcohcytiefa.us-east-1.cloudsearch.amazonaws.com
  doc_endpoint: http://doc-ml-test-desuye5rn55qjlzjcohcytiefa.us-east-1.cloudsearch.amazonaws.com

test:
  secret_key_base: 9c76bfde0fd27c7c03227c875e52db3e751c2d17d0991bb53ff72ccdf78380d1eaf83db9a52dbd147b2befdcabac85334f8e531de700c0d68c5cbaa8c0599225
  aws_key_id: fake
  aws_secret_key: fake
  csd_endpoint: fake

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_key_id: <%= ENV["AWS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  csd_endpoint: http://search-ml-test-desuye5rn55qjlzjcohcytiefa.us-east-1.cloudsearch.amazonaws.com
  doc_endpoint: http://doc-ml-test-desuye5rn55qjlzjcohcytiefa.us-east-1.cloudsearch.amazonaws.com
